# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - photosharestorag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ''

      - name: Install Python dependencies
        run: |
          python -m venv env
          .\\env\\Scripts\\activate
          pip install -r requirements.txt

      - name: Zip the application files
        run: Compress-Archive .\\* app.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4512059F1FF477C9F860F3290D4EA43 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_204CF98CA44443229F4ED4BCD15F6656 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6F6F6E3CD624D80A9F0792541A6A731 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'photosharestorag'
          slot-name: 'Production'
          package: '.\\app.zip'
          